AWSTemplateFormatVersion: 2010-09-09

Description: Template to create a VPC.

Resources:
  VPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/26
      Tags:
      - Key: Name
        Value: My-CF-VPC
